export const API_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "internalServerError",
  UNAUTHORIZED: "unauthorized",
  ACCOUNT_NOT_FOUND: "accountNotFound",
  INVALID_PASSWORD: "invalidPassword",
  ACCOUNT_SUSPENDED: "accountSuspended",
  INVALID_ROLE: "invalidRole",
  EMAIL_ALREADY_IN_USE: "emailAlreadyInUse",
  FAILED_TO_CREATE_ACCOUNT: "failedToCreateAccount",
  ADMIN_ACCESS_REQUIRED: "adminAccessRequired",
  JOB_ID_REQUIRED: "jobIdRequired",
  APPLICATION_ID_REQUIRED: "applicationIdRequired",
  COMPANY_ID_REQUIRED: "companyIdRequired",
  TESTIMONIAL_ID_REQUIRED: "testimonialIdRequired",
  MESSAGE_ID_REQUIRED: "messageIdRequired",
  SUBMISSION_ID_REQUIRED: "submissionIdRequired",
  USER_ID_REQUIRED: "userIdRequired",
  JOB_NOT_FOUND: "jobNotFound",
  ONLY_JOB_SEEKERS_CAN_APPLY: "onlyJobSeekersCanApply",
  ALREADY_APPLIED: "alreadyApplied",
  APPLICATION_NOT_FOUND: "applicationNotFound",
  FAILED_TO_UPDATE_APPLICATION: "failedToUpdateApplication",
  FAILED_TO_DELETE_APPLICATION: "failedToDeleteApplication",
  INVALID_APPLICATION_STATUS: "invalidApplicationStatus",
  FAILED_TO_UPDATE_APPLICATION_STATUS: "failedToUpdateApplicationStatus",
  FAILED_TO_DELETE_JOB: "failedToDeleteJob",
  ONLY_JOB_SEEKERS_CAN_SAVE: "onlyJobSeekersCanSave",
  ONLY_JOB_SEEKERS_CAN_VIEW_SAVED: "onlyJobSeekersCanViewSaved",
  COMPANY_NOT_FOUND: "companyNotFound",
  TESTIMONIAL_NOT_FOUND: "testimonialNotFound",
  USER_NOT_FOUND: "userNotFound",
  MESSAGE_NOT_FOUND: "messageNotFound",
  CANNOT_CHANGE_OWN_ADMIN_ROLE: "cannotChangeOwnAdminRole",
  CANNOT_SUSPEND_OWN_ACCOUNT: "cannotSuspendOwnAccount",
  CANNOT_REMOVE_LAST_ADMIN: "cannotRemoveLastAdmin",
  CANNOT_SUSPEND_LAST_ADMIN: "cannotSuspendLastAdmin",
  TEAM_SIZE_MIN_EXCEEDS_MAX: "teamSizeMinExceedsMax",
  PROFILE_IMAGE_NOT_FOUND: "profileImageNotFound",
  SUBMISSION_NOT_FOUND: "submissionNotFound",
  FILE_REQUIRED: "fileRequired",
  FILE_SIZE_EXCEEDS: "fileSizeExceeds",
  FILE_TYPE_NOT_SUPPORTED: "fileTypeNotSupported",
  TOO_MANY_REQUESTS: "tooManyRequests",
  INVALID_CSRF_TOKEN: "invalidCsrfToken",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
