import type { Metadata } from "next";
import { Cairo, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/shared/Header/Header";
import LocaleProviders from "@/providers/LocaleProviders";
import MobileMenu from "@/components/shared/Header/MobileMenu";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const CairoFont = Cairo({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
  style: ['normal'],
  subsets: ['latin', 'arabic'],
  variable: '--font-cairo'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const locale = (await params).locale;
  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={cn("h-full", "antialiased", CairoFont.variable)}
    >
      <body className="min-h-full flex flex-col">
        <LocaleProviders>
          <Header />
          <MobileMenu />
          <main className="flex-1">
            {children}
          </main>
          {/* <Footer /> */}
        </LocaleProviders>
      </body>
    </html>
  );
}
